# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=140, null=True)),
                ('country', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=350)),
                ('pages', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.CharField(max_length=5)),
                ('count', models.PositiveIntegerField()),
                ('img_link', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(default='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booksapp.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together=set([('group', 'slug')]),
        ),
    ]
