# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='img_link',
            new_name='imageLink',
        ),
        migrations.RemoveField(
            model_name='books',
            name='date',
        ),
        migrations.AddField(
            model_name='books',
            name='year',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
