# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_auto_20180620_1424'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='language',
            name='group',
        ),
        migrations.AlterField(
            model_name='books',
            name='language',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
